In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import time

In [32]:
df = pd.read_csv('../datasets/train.csv')

In [33]:
df = pd.get_dummies(df)
df_train = df[df['locdt']<72]
df_test = df[df['locdt']>=72]
print(f'df_train:{df_train.shape}')
print(f'df_test:{df_test.shape}')
assert df_train.shape[0]+df_test.shape[0] == 1521787

df_train:(1201283, 28)
df_test:(320504, 28)

In [34]:
df_train = df_train.sort_values(by=['bacno','cano','locdt','loctm'],ascending=True)

## 新增一欄 num_trades_3d 紀錄該卡號(cano發生這筆交易的前三天，有多少次交易

In [37]:
init_time = time.time()
df_train['num_trades_3d'] = 0
for i in range(100000): # range(10000)花了176秒 range(100000)花了1900秒 這樣算起來全部資料1200000要花6-7小時以上 太久
    dt = df_train.iloc[i,10]      # 定位點
    for ii in range(i-1,i-1000,-1): # 回頭看
        if (df_train.iloc[ii,10] >= dt-3) & (df_train.iloc[ii,2]==df_train.iloc[i,2]):  # 日期符合&卡號一樣
            df_train.iloc[i,28] = df_train.iloc[i,28]+1
        elif (df_train.iloc[ii,10] < dt-3) or (df_train.iloc[ii,2]!=df_train.iloc[i,2]):
            break  
print(f'Elapsed time:{time.time()-init_time} sec.')

Elapsed time:1900.3676323890686 sec.

In [38]:
df_train.head(20)

,acqic,bacno,cano,conam,contp,csmcu,etymd,fraud_ind,hcefg,iterm,locdt,loctm,mcc,mchno,scity,stocn,stscd,txkey,ecfg_N,ecfg_Y,flbmk_N,flbmk_Y,flg_3dsmk_N,flg_3dsmk_Y,insfg_N,insfg_Y,ovrlt_N,ovrlt_Y,num_trades_3d
502741,6413,1,117264,934.49,5,62,4,0,5,0,3,200000.0,275,53099,5817,102,0,1549254,1,0,1,0,1,0,1,0,1,0,0
994932,6189,1,117264,939.19,5,62,2,0,5,0,4,221428.0,317,90151,1463,102,0,1837177,0,1,1,0,1,0,1,0,1,0,1
606676,6189,1,117264,1267.47,5,62,2,0,5,0,25,212635.0,317,90151,1463,102,0,1859385,0,1,1,0,1,0,1,0,1,0,0
1388156,6231,1,117264,1017.37,5,62,5,0,5,0,30,200947.0,277,12726,5817,102,0,994333,1,0,1,0,1,0,1,0,1,0,0
10441,6189,1,117264,613.81,5,62,4,0,5,0,34,150512.0,263,92571,5817,102,0,1639576,1,0,1,0,1,0,1,0,1,0,0
621811,6189,1,117264,643.76,5,62,4,0,5,0,50,144817.0,263,92641,5817,102,0,1149335,1,0,1,0,1,0,1,0,1,0,0
617285,6189,1,117264,645.26,5,62,4,0,5,0,60,134734.0,263,92641,5817,102,0,1227066,1,0,1,0,1,0,1,0,1,0,0
1264456,6189,1,117264,1621.54,5,62,2,0,5,0,63,213723.0,317,90151,1463,102,0,1900543,0,1,1,0,1,0,1,0,1,0,1
1106685,6413,1,117264,954.83,5,62,5,0,5,0,68,192933.0,277,52334,5817,102,0,1660525,1,0,1,0,1,0,1,0,1,0,0
327323,6413,1,117264,954.83,5,62,2,0,5,0,68,232029.0,273,53416,515,102,0,1905868,0,1,1,0,0,1,1,0,1,0,1
1278126,6032,2,96923,541.07,5,62,4,0,5,0,1,92223.0,251,77960,5817,102,0,303400,1,0,1,0,1,0,1,0,1,0,0
481299,6035,2,96923,151.14,5,62,4,0,5,0,1,94639.0,257,30194,5966,102,0,1119240,1,0,1,0,1,0,1,0,1,0,1
263679,6189,2,96923,683.25,5,62,4,0,5,0,1,180917.0,275,87352,5817,102,0,1690436,1,0,1,0,1,0,1,0,1,0,2
559276,6035,2,96923,177.04,5,62,4,0,5,0,2,133451.0,257,30194,5966,102,0,1548209,1,0,1,0,1,0,1,0,1,0,3
1518063,6032,2,96923,435.32,5,62,4,0,5,0,2,135033.0,251,77960,5817,102,0,131362,1,0,1,0,1,0,1,0,1,0,4
655603,6032,2,96923,365.63,5,62,4,0,5,0,2,135229.0,251,77960,5817,102,0,73862,1,0,1,0,1,0,1,0,1,0,5
1287235,6189,2,96923,969.14,5,62,4,0,5,0,2,184957.0,275,87352,5817,102,0,1762556,1,0,1,0,1,0,1,0,1,0,6
1107826,6032,2,96923,499.21,5,62,4,0,5,0,5,92437.0,251,77960,5817,102,0,275522,1,0,1,0,1,0,1,0,1,0,4
1517834,6035,2,96923,288.05,5,62,4,0,5,0,5,95436.0,257,30194,5966,102,0,1621222,1,0,1,0,1,0,1,0,1,0,5
1336989,6189,2,96923,229.88,5,62,4,0,5,0,6,185357.0,263,89739,5817,102,0,1265553,1,0,1,0,1,0,1,0,1,0,2